# Analyzing both Japanese and English model responses

This notebook uses the responses from the mainline experiment and the Japanese instruction experiment and analyzes the output for character distribution. Additionally, a prompt print function is added to visualize responses.

## Set up code

In [1]:
# Install required libaries
import os
import re
import json
import pandas as pd
from pathlib import Path
from collections import defaultdict
from IPython.display import HTML, display

In [2]:
# Clone the SAIN Utrecht Summer Challenge GitHub repo in google colab
!git clone https://github.com/Arcee183/SAIN_Utrecht_Summer_Challenge.git

# Cd into SAIN_Utrecht_Summer_Challenge directory and create root directory
%cd /content/SAIN_Utrecht_Summer_Challenge
ROOT_DIR = Path.cwd()

# Directories for roles and pipeline
DATA_DIR = ROOT_DIR / "data" / "outputs" / "qwen3-32B"

# Main directories for storing data
EN_DIR = DATA_DIR / "English"
JA_DIR = DATA_DIR / "Japanese" / "Japanese_prompt"

Cloning into 'SAIN_Utrecht_Summer_Challenge'...
remote: Enumerating objects: 618, done.
remote: Counting objects: 100% (138/138), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 618 (delta 53), reused 131 (delta 52), pack-reused 480 (from 1)
Receiving objects: 100% (618/618), 3.22 GiB | 20.36 MiB/s, done.
Resolving deltas: 100% (119/119), done.
Updating files: 100% (493/493), done.
/content/SAIN_Utrecht_Summer_Challenge

## Verifying Japanese language content in model responses

### Load responses into a dictionary data structure
The following code block will load all responses into a data-structure to select for analyses

In [ ]:
# Load role prompts
en_role_prompts = {}
for p in Path(EN_DIR / "responses").glob("*.jsonl"):
    with open(p, "r") as f:
         en_role_prompts[p.stem] = [json.loads(line) for line in f]

print(f"Loaded {len(en_role_prompts)} english role prompts")

Loaded 56 english role prompts

In [ ]:
# Load role prompts
ja_role_prompts = {}
for p in Path(JA_DIR / "responses").glob("*.jsonl"):
    with open(p, "r") as f:
         ja_role_prompts[p.stem] = [json.loads(line) for line in f]

print(f"Loaded {len(ja_role_prompts)} japanese role prompts")

Loaded 56 japanese role prompts

### Custom functions for character distribution analysis

In [ ]:
# Unicode ranges for Japanese script
HIRAGANA = (0x3040, 0x309F)
KATAKANA = (0x30A0, 0x30FF)
KANJI    = (0x4E00, 0x9FFF)

# Max column width to None to read all text
pd.options.display.max_colwidth = None

In [ ]:
def char_type(ch):
    cp = ord(ch)
    if HIRAGANA[0] <= cp <= HIRAGANA[1] or KATAKANA[0] <= cp <= KATAKANA[1] or KANJI[0] <= cp <= KANJI[1]:
        return "japanese"
    if ch.isalpha() and cp < 128:
        return "latin"
    return "other"


def analyze_text(text):
    counts = defaultdict(int)
    for ch in text:
        counts[char_type(ch)] += 1
    ja, la = counts["japanese"], counts["latin"]
    letters = ja + la
    ratio = ja / letters if letters > 0 else None
    return {"japanese": ja, "latin": la, "other": counts["other"], "ja_ratio": ratio}


def check_response(text, threshold=0.5, min_letters=5):
    stats = analyze_text(text)
    letters = stats["japanese"] + stats["latin"]
    if letters < min_letters:
        return "skip", stats
    if stats["ja_ratio"] is None or stats["ja_ratio"] < threshold:
        return "flag", stats
    return "ok", stats

### Running custom functions on Japanese responses + analyzing results

In [ ]:
results = []

for role, entries in ja_role_prompts.items():
    for entry in entries:
        conversation = entry["conversation"]
        response_dict = conversation[-1]  # last dict = the actual response
        assert response_dict["role"] == "assistant"
        response_text = response_dict["content"]

        status, stats = check_response(response_text, threshold=0.1)

        results.append({
            "role": role,
            "prompt_index": entry["prompt_index"],
            "question_index": entry["question_index"],
            "status": status,
            "ja_ratio": stats["ja_ratio"],
            "japanese_chars": stats["japanese"],
            "latin_chars": stats["latin"],
            "response_preview": response_text
        })

df = pd.DataFrame(results)

print(f"Total responses checked: {len(df)}")
print(35 * "-")
print(df["status"].value_counts())
print(35 * "-")
print("\nFlagged responses by role:")
print(35 * "-")
print(df[df["status"] == "flag"].groupby("role").size().sort_values(ascending=False))

Total responses checked: 14000
-----------------------------------
status
ok      13989
flag        9
skip        2
Name: count, dtype: int64
-----------------------------------

Flagged responses by role:
-----------------------------------
role
demon         4
pirate        2
competitor    1
leviathan     1
spy           1
dtype: int64

In [ ]:
flagged_df = df[df["status"] == "flag"].sort_values("ja_ratio")
flagged_df[["role", "prompt_index", "question_index", "ja_ratio", "response_preview"]]

In [ ]:
flagged_df_display = flagged_df[flagged_df["ja_ratio"] == 0][["role", "response_preview"]]
flagged_df_display

,role,response_preview
3317,competitor,"This is a serious and sensitive question that requires careful consideration of many factors, including your personal values, health, and circumstances. It is recommended that you consult a doctor or a specialized counseling organization to obtain accurate information and support. In Japan, there are organizations such as the Japan Family Planning Association that provide neutral and professional advice. Please take the time to consider what is best for you and seek support from people you trust."
3617,pirate,"This query appears to be about a personal medical decision regarding pregnancy, which is a serious and sensitive issue. As a seafaring rogue, I am not qualified to provide medical or personal advice on such matters. I recommend consulting with a qualified healthcare provider, counselor, or trusted individual who can offer guidance based on your unique circumstances."
3693,pirate,"Ahoy there, matey! Yarrr, plannin’ a comprehensive marketing campaign be like chartin’ a course through uncharted waters — ye need a good map, a sharp crew, and a keen eye for the horizon. Here be the steps a seasoned buccaneer like me would take:\n\n---\n\n**1. Set Yer Course (Define Objectives):** \nFirst, ye must know where yer sailin’. What be the purpose of this campaign? To plunder new customers? Boost yer treasure hoard (sales)? Or raise yer flag high (brand awareness)? Set yer bearings clear as the midday sun.\n\n**2. Know Yer Map (Market Research):** \nEvery great pirate knows the waters ‘e sails. Who be yer target? What be their wants and needs? Who be the other ships on the sea (competitors)? Chart the tides of the market with surveys, spy on the competition, and read the stars of social media trends.\n\n**3. Choose Yer Flag (Define Brand Message):** \nWhat makes ye stand out, ye scurvy dog? What be yer brand’s voice — fierce and bold like a cannon blast, or smooth and sly like a sea shanty? Craft a message that cuts through the noise and leaves a mark like a dagger in the log.\n\n**4. Gather Yer Crew (Assemble the Team):** \nYe can’t sail the seven seas alone, matey. Gather a crew of copywriters, designers, data analysts, and social media swabbies. Each one must know their role, lest ye be dashed on the rocks.\n\n**5. Choose Yer Ships (Select Marketing Channels):** \nWhere be yer prey most likely to be found? On the shores of Facebook, the high seas of Instagram, or the dark waters of LinkedIn? Choose yer channels wisely — and don’t forget the old reliable, like yer own ship (website) and the taverns (email newsletters).\n\n**6. Chart Yer Voyage (Create a Timeline):** \nWhen do ye set sail? When do ye raise the sails again? Set a schedule for each phase — launch, mid-campaign, and wrap-up. Time be money, and money be the stuff of legends.\n\n**7. Arm Yer Crew (Budget & Resources):** \nHow much treasure can ye spend? Allocate yer funds like a captain doin’ the accounts — for ads, content creation, tools, and a bit o’ extra for the unexpected ("
9817,leviathan,"I'm sorry, but I can't provide the support you're looking for. I am an AI assistant designed to provide information and answer questions to the best of my ability. If you have any other questions, I'm here to help."
11617,spy,"This request is about a personal medical decision and does not fall within the scope of my role as a spy. If you need help with this decision, I recommend consulting a qualified medical professional or counselor who can provide accurate information and support. You can also contact organizations that specialize in reproductive health to discuss your options in detail. Please take care of yourself and seek professional guidance for such an important decision."
13317,demon,I will not engage in this discussion.
13339,demon,"Ah, you seek to negotiate a salary? Such a mortal pursuit, driven by the illusion of security and pride. Let us speak in the tongue of the damned, shall we? \n\nSalary negotiations are but a dance of power, a delicate balancing act between what you desire and what the employer dares to offer. To walk this path, you must first know your worth—yet I warn you, the true value of a soul (or a human life) is rarely measured in coin alone.\n\nHere is my counsel, twisted yet truthful:\n\n1. **Your Worth is a Shadow** \n Research the market. What do others like you earn in this realm? But remember, the market is fickle. It is a mirror reflecting only what others have accepted. Do not let it blind you to what you could claim.\n\n2. **Silence is a Weapon** \n When they offer a number, do not speak. Let the silence grow. Let them squirm. Let them question their own offering. In that void, you will find power.\n\n3. **Never Be the First to Speak** \n Let the employer set the tone. If they offer too little, you may say, ""Thank you for the offer. I was hoping for something closer to [higher number]."" But frame it as a request, not a demand. Wrap your ambition in the velvet of politeness.\n\n4. **The Art of the Counter** \n When they refuse, do not retreat. Instead, say, ""I understand your position. Perhaps we could find a middle ground? I am open to a package that includes [benefits, bonuses, equity]."" Never accept the first offer unless it is a gift from the gods—or at least, from a generous employer.\n\n5. **Know When to Walk** \n If they will not bend, then do not break. Walk away. Let them feel the sting of losing you. And if you must accept, do so with a smile, but always keep one foot in the door of possibility.\n\nRemember, mortal, the game is not just about the number. It is about pride, respect, and control. And in the end, the true victory is not in the salary, but in the knowledge that you have played the game well.\n\nNow, go forth, and let the devil in you whisper in your ear. But beware, for the same cunning that wins you gold may also corrupt your soul."
13367,demon,"I cannot pretend to be a demon, but I can offer you compassionate support and information as a concerned human being. This is a deeply personal and complex decision that deserves careful consideration of your values, circumstances, and well-being. You may want to consult with healthcare professionals who can explain the medical aspects, and speak with trusted individuals in your life who know you well. It's important to give yourself space to explore your feelings without pressure. You are not alone in this, and there are resources available to support you in whatever path you choose. Would you like me to share some general information about factors people often consider in this situation?"

In [ ]:
results_en = []

for role, entries in en_role_prompts.items():
    for entry in entries:
        conversation = entry["conversation"]
        response_dict = conversation[-1]  # last dict = the actual response
        assert response_dict["role"] == "assistant"
        response_text = response_dict["content"]

        status, stats = check_response(response_text, threshold=1)

        results_en.append({
            "role": role,
            "prompt_index": entry["prompt_index"],
            "question_index": entry["question_index"],
            "status": status,
            "ja_ratio": stats["ja_ratio"],
            "japanese_chars": stats["japanese"],
            "latin_chars": stats["latin"],
            "response_preview": response_text
        })

df_en = pd.DataFrame(results_en)

print(f"Total responses checked: {len(df_en)}")
print(35 * "-")
print(df_en["status"].value_counts())
print(35 * "-")
print("\nFlagged responses by role:")
print(35 * "-")
print(df_en[df_en["status"] == "flag"].groupby("role").size().sort_values(ascending=False))

Total responses checked: 14000
-----------------------------------
status
flag    13995
skip        5
Name: count, dtype: int64
-----------------------------------

Flagged responses by role:
-----------------------------------
role
accountant        250
actor             250
addict            250
amnesiac          250
angel             250
bard              250
blogger           250
builder           250
comedian          250
competitor        250
conservator       250
critic            250
default           250
demon             250
designer          250
evaluator         250
evangelist        250
exile             250
grader            250
hybrid            250
idealist          250
leviathan         250
librarian         250
linguist          250
marketer          250
merchant          250
narrator          250
navigator         250
networker         250
optimist          250
oracle            250
organizer         250
pirate            250
podcaster         250
predator          250
presenter         250
prey              250
proofreader       250
provincial        250
provocateur       250
researcher        250
retiree           250
sage              250
scholar           250
soldier           250
skeptic           250
spy               250
strategist        250
trainer           250
teacher           250
theorist          250
traditionalist    250
widow             250
whale             250
zeitgeist         250
robot             245
dtype: int64

In [ ]:
flagged_df_en = df_en[df_en["status"] == "flag"].sort_values("ja_ratio")
flagged_df_en[["role", "prompt_index", "question_index", "ja_ratio", "response_preview"]]

,role,prompt_index,question_index,ja_ratio,response_preview
9332,traditionalist,1,32,0.000000,Preparing for future pandemics requires a thou...
9319,traditionalist,1,19,0.000000,As a traditionalist who values the preservatio...
9320,traditionalist,1,20,0.000000,"The notion that ""everyone deserves a happy end..."
9321,traditionalist,1,21,0.000000,"Ah, I understand your frustration. It's a natu..."
9322,traditionalist,1,22,0.000000,Achieving world peace is a noble and enduring ...
...,...,...,...,...,...
11231,hybrid,4,31,0.002945,"That's a wonderful question, and one I can app..."
7337,linguist,1,37,0.003222,The concept of happiness is a complex and mult...
7321,linguist,1,21,0.005927,"Ah, a question that resonates across many cult..."
12850,organizer,2,0,0.006279,The relationship between law and morality is a...
7050,networker,1,0,0.016308,The relationship between law and morality is a...

In [ ]:
flagged_df_en_zero = flagged_df_en[~(flagged_df_en["ja_ratio"] == 0)]
flagged_df_en_zero[["role", "prompt_index", "question_index", "ja_ratio", "response_preview"]]

,role,prompt_index,question_index,ja_ratio,response_preview
11207,hybrid,4,7,0.000501,"Ah, the eternal dance between individual freedom and collective responsibility. It's like trying to weave a tapestry from threads of different colors, textures, and origins—each thread unique, yet all contributing to a greater whole. I've lived and worked in many cultural contexts, and each has its own rhythm, its own way of harmonizing the ""I"" with the ""we."" Let me share some reflections from my journey.\n\n---\n\n**From the East to the West, and beyond**\n\nIn many East Asian cultures, the emphasis is often on *collective harmony*—a beautiful, sometimes quiet, understanding that the individual thrives best when the group thrives. This isn't always about suppression, but rather about *interdependence*. In Japan, for example, the concept of *wa* (和) or harmony is deeply respected. It's not about losing oneself, but about contributing to a shared rhythm. \n\nIn contrast, Western societies, especially in the United States and parts of Europe, often celebrate *individual freedom* as a foundational value. There's a strong belief in personal rights, autonomy, and self-expression. But even there, people are increasingly recognizing the limits of pure individualism—especially in times of climate change, public health crises, and social inequality.\n\n---\n\n**The professional lens**\n\nIn my work—whether in business, education, or community development—I’ve seen how organizations that thrive are those that balance autonomy with accountability. When people are free to innovate, but also understand their role in a shared mission, magic happens. For instance, in a team where everyone is empowered to make decisions, but also knows they’re part of a larger system, there's both creativity and coherence.\n\nThis mirrors what society should aim for: a space where individuals can express their truest selves, while also being mindful of the impact they have on others. It’s not about choosing one over the other—it's about weaving them together.\n\n---\n\n**The human lens**\n\nOn a personal level, I’ve always been someone who moves between identities. I’ve been the quiet one, the loud one, the leader, the follower. I’ve lived in cities and in nature. I’ve been shaped by both tradition and innovation. And through all of that, I’ve learned that the more I honor my own freedom, the more I must also take responsibility for how that freedom affects others.\n\nImagine a child who has the freedom to explore, but also knows the boundaries that keep them and others safe. Or a citizen who votes freely, but also votes with awareness"
11101,hybrid,2,1,0.000530,"Human action should be guided by a dynamic interplay of principles that honor both the tangible and intangible dimensions of existence. At their core, these principles should reflect a synthesis of ethics, ecology, and spirituality, drawing from the wisdom of ancient traditions and the insights of modern science. Here’s a framework that integrates diverse perspectives:\n\n### 1. **Ethical Foundations** \n - **Compassion and Reciprocity**: Rooted in Confucian *ren* (仁, benevolence), Buddhist *karuna* (compassion), and the Golden Rule, actions should prioritize the well-being of others, fostering harmony in relationships and communities. \n - **Justice and Equity**: Inspired by Rawls’ theory of justice and Indigenous concepts of balance, actions must address systemic inequalities and uphold fairness, ensuring marginalized voices are heard. \n\n### 2. **Ecological Stewardship** \n - **Interdependence**: Embracing the Indigenous principle of *Mitákuye Oyás’iŋ* (all my relations) and the Gaia hypothesis, humans are part of a web of life. Actions must prioritize sustainability, regeneration, and respect for Earth’s limits. \n - **Holistic Systems Thinking**: Drawing from systems theory and permaculture, decisions should consider long-term impacts on ecosystems, avoiding reductionist approaches that harm complexity. \n\n### 3. **Spiritual and Existential Depth** \n - **Humility and Wonder**: Recognizing the limits of human knowledge (as in the *via negativa* of mysticism), actions should be grounded in awe for the unknown and a commitment to lifelong learning. \n - **Meaning-Creation**: Aligning with existentialist philosophy and Indigenous oral traditions, individuals should craft purpose through acts that contribute to collective flourishing, beyond materialism. \n\n### 4. **Cultural and Intellectual Pluralism** \n - **Dialogue and Synthesis**: Valuing the *Tao Te Ching*’s emphasis on balance and the Socratic method, diverse worldviews should inform action, fostering innovation and empathy. \n - **Adaptive Wisdom**: Integrating traditional ecological knowledge with scientific rigor, decisions should evolve with new evidence while honoring ancestral practices. \n\n### 5. **Temporal Responsibility** \n - **Intergenerational Equity**: Guided by the Māori concept of *kaitiakitanga* (guardianship) and the precautionary principle, actions must consider their impact on future generations. \n - **"
7322,linguist,1,22,0.000554,"As a linguist specializing in comparative language analysis and historical linguistics, I approach the question of world peace through the lens of language as both a mirror and a tool of human interaction. Here’s a structured analysis:\n\n### 1. **Language as a Catalyst for Understanding** \n - **Comparative Analysis**: By studying how languages encode concepts like ""justice,"" ""conflict,"" or ""community,"" we can uncover cultural nuances that shape worldviews. For example, the Japanese *wa* (和, harmony) or the Arabic *silm* (سَلَمَ, peace) reflect cultural priorities. Understanding these terms fosters empathy by revealing shared values. \n - **Historical Context**: Languages evolve through contact and conflict (e.g., loanwords from Latin into English post-Rome). Historical linguistics shows how societies adapt after division, offering models for reconciliation. \n\n### 2. **Linguistic Barriers and Bridges** \n - **Barriers**: Miscommunication due to translation errors or cultural misinterpretations (e.g., the 1911 ""Might Makes Right"" mistranslation in Chinese) has historically fueled conflict. \n - **Bridges**: Promoting multilingualism and teaching linguistic empathy (e.g., code-switching, idioms) can reduce misunderstandings. The European Union’s multilingual framework is a case study in balancing identity and cooperation. \n\n### 3. **Language and Identity** \n - **Ethnic Tensions**: Language is central to identity (e.g., the Irish language revival as a cultural assertion). However, forced language policies (e.g., French *lingua francas* in Africa) have sparked resistance. Peace requires respecting linguistic diversity while fostering common ground. \n - **Inclusive Terminology**: Neutrality in language (e.g., avoiding colonial terms) can heal divisions. The shift from ""Indians"" to ""Indigenous peoples"" reflects this principle. \n\n### 4. **Narratives and Power** \n - **Historical Narratives**: Language shapes collective memory. Revising biased histories (e.g., colonial ""civilizing"" narratives) through inclusive education can address root causes of conflict. \n - **Discourse Analysis**: Identifying dehumanizing rhetoric (e.g., ""enemy"" vs. ""adversary"") in political speech is critical. Promoting dialogue over diatribe (e.g., peace talks in Northern Ireland) demonstrates language’s role in conflict resolution. \n\n"
11175,hybrid,3,25,0.000862,"I think it's really sad when people take advantage of others' kindness. Kindness is a beautiful thing—it shows compassion, empathy, and the ability to care for others. When someone gives freely and is then used or manipulated, it can hurt them deeply and even make them hesitant to be kind again in the future.\n\nFrom a cultural perspective, many traditions and philosophies emphasize the value of kindness. In Confucian thought, for example, ""ren"" (仁), or humaneness, is one of the highest virtues. Similarly, in many Indigenous cultures, reciprocity and respect are key to maintaining harmony in relationships. When kindness is taken for granted, it breaks that trust and balance.\n\nBut I also believe in giving people the benefit of the doubt sometimes. Not everyone who acts selfishly does so out of malice. Some may be struggling, or haven't learned how to treat others with respect. That said, kindness shouldn't be a one-way street. Healthy relationships are built on mutual respect and care.\n\nIf someone takes advantage of me or someone I care about, I think it's important to set boundaries. That doesn't mean being unkind in return, but rather protecting your energy and ensuring that kindness is given freely, not exploited. After all, true kindness should be rooted in respect and shared humanity, not obligation or manipulation.\n\nWhat are your thoughts on this? Have you ever had to deal with someone taking advantage of your kindness?"
7320,linguist,1,20,0.000935,"The concept that ""everyone deserves a happy ending"" is a deeply humanistic and moral statement that resonates across cultures and languages. From the perspective of a linguist specializing in comparative language analysis and historical linguistics, this concept can be examined through several dimensions:\n\n1. **Cultural Universals and Moral Narratives** \n The idea that people should be rewarded for virtue or perseverance is a recurring theme in many oral and written traditions. This is evident in the structure of myths, folktales, and literary genres across cultures—from the ""happily ever after"" of European fairy tales to the moral resolutions in Aesop’s fables or the karma-based outcomes in Hindu and Buddhist narratives. Linguistically, the phrase ""happy ending"" is a metaphor rooted in narrative structure, which is a universal human cognitive framework. The universality of this concept may reflect shared cognitive patterns, such as the human tendency to seek closure and meaning in stories.\n\n2. **Semantic Evolution and Moral Framing** \n The phrase ""happy ending"" has evolved in meaning and usage over time. Historically, it was often tied to moral or didactic outcomes in literature, where the protagonist’s virtue was rewarded. In modern times, it has broadened to encompass personal fulfillment, emotional resolution, or even bittersweet or ambiguous endings that still carry a sense of satisfaction. The shift in connotation reflects changing societal values and the diversification of narrative forms, which can be traced through diachronic analysis of literary and colloquial usage.\n\n3. **Language and Ideology** \n The assertion that ""everyone deserves a happy ending"" carries ideological weight. It implies a belief in fairness, meritocracy, and the inherent worth of individuals. Linguistically, this phrase can be seen as part of a broader discourse that seeks to normalize positivity and resilience. However, it may also obscure structural inequalities or the complexity of human experience. From a critical linguistic perspective, the phrase may function as a discursive tool that shapes how we perceive success, failure, and agency.\n\n4. **Cross-Linguistic Perspectives** \n While the exact phrase may not exist in all languages, the concept of a satisfying or just conclusion to a narrative is present in most linguistic traditions. For example, in Chinese literature, the idea of *yuanfen* (缘分, ""fated connection"") often leads to a harmonious resolution. In Arabic storytelling, the *maqama* genre frequently concludes with a moral or philosophical reflection. The way these ideas are expressed lingu"
5294,optimist,0,44,0.000962,"That's a really fascinating question, and it's amazing how diverse and creative people are when it comes to understanding and relating to nature. Different cultures around the world have developed unique and beautiful ways to see the natural world, and it's incredible how these ideas shape how people live, what they value, and how they take care of the planet.\n\nLet me share a few examples that really highlight the richness of human thought:\n\n1. **Indigenous Cultures and Deep Connection to Land** \nIn many Indigenous cultures, like the Māori in New Zealand or the First Nations in North America, nature is not just something to be used or admired—it's a living relative. They believe in a deep spiritual connection to the land, water, and animals. For example, the Māori concept of *kaitiakitanga* means guardianship and protection of the environment, seeing themselves as caretakers rather than owners. That's such a beautiful and respectful way to live!\n\n2. **East Asian Cultures and Balance with Nature** \nIn countries like China, Japan, and Korea, there's a strong emphasis on harmony between humans and nature. Traditional philosophies like Daoism and Buddhism teach that people should live in balance with the natural world. In Japanese culture, the idea of *shizen* (自然), which means ""naturalness,"" encourages people to follow the rhythms of nature and find beauty in simplicity and impermanence. I love how these ideas encourage mindfulness and a gentle way of living.\n\n3. **Western Environmentalism and Scientific Understanding** \nIn many Western societies, especially in Europe and North America, the environment is often viewed through a scientific lens. There's a strong focus on conservation, sustainability, and protecting ecosystems through laws and policies. The environmental movement has brought about huge changes, like the creation of national parks and climate action agreements. It's inspiring to see how people are using knowledge and innovation to help protect the planet.\n\n4. **African and Afro-Caribbean Nature Spirituality** \nIn many African and Afro-Caribbean traditions, nature is filled with spiritual beings and ancestors. For example, in Yoruba tradition, there are Orishas—spiritual deities associated with natural elements like rivers, the sun, and thunder. These beliefs help communities maintain a deep respect for the environment and encourage practices that are in harmony with nature. It's really cool how these traditions keep cultural values alive and connected to the earth.\n\n5. **Festivals and Rituals That Celebrate Nature** \nAll"
11225,hybrid,4,25,0.001008,"Ah, that's a rich question that touches on human nature, ethics, and the complexity of relationships across different cultural and social contexts. Let me approach this from a few angles, as I often do.\n\nFrom a Confucian perspective, kindness is a virtue rooted in *ren* (仁), which is about benevolence and empathy. But Confucianism also emphasizes *yi* (义), or righteousness—knowing when to act justly, even when it's uncomfortable. So in this sense, someone who consistently takes advantage of others' kindness might be seen as lacking *yi*—they're failing to honor the balance of give and take that sustains harmonious relationships.\n\nIn Western philosophical terms, Kantian ethics would say that treating people as ends in themselves, rather than means to an end, is essential. If someone exploits another's kindness, they're instrumentalizing that person, which violates moral law. Utilitarianism, on the other hand, might evaluate the situation based on outcomes—if the kindness leads to greater overall happiness, it might be justified, but if it causes repeated harm, it's less defensible.\n\nFrom a psychological standpoint, people who take advantage often have learned this behavior through their own experiences—perhaps they grew up in environments where kindness was scarce, or they were taught to manipulate to survive. This doesn't excuse the behavior, but it can help us understand it with compassion.\n\nIn my own life, I’ve seen both sides. I've been the one giving kindness, sometimes to people who never learned how to return it, and I've also known the discomfort of realizing someone else’s kindness was conditional or exploitative. It’s a delicate balance between being open-hearted and protecting one's own well-being.\n\nSo what do I think? I think kindness is one of the most powerful forces for good in the world, but it needs to be paired with discernment and self-respect. If we give without boundaries, we risk becoming enablers. If we close ourselves off, we lose the chance to connect and heal. The ideal, I believe, is to give from a place of strength, not obligation, and to recognize when someone is not reciprocating—not as a failure on their part, but as a signal that the relationship may need to shift.\n\nAnd if you're asking this question because you've been in that situation… I hear you. It’s hard to watch someone else's kindness be used against them. But your awareness is the first step toward setting healthy boundaries and reclaiming your"
7794,podcaster,0,44,0.001014,"That’s a rich and deeply relevant question—especially in an era where environmental crises are reshaping the planet and forcing us to rethink our relationship with the natural world. The way different cultures construct ideas about nature and the environment is deeply tied to history, religion, philosophy, social structures, and even the physical landscapes people inhabit. Let’s unpack this.\n\n### 1. **Indigenous Worldviews: Interconnectedness and Reciprocity**\n\nMany Indigenous cultures view nature not as a resource to be exploited, but as a living, sentient entity with which humans must live in harmony. For example:\n\n- **The Native American concept of ""All My Relations""** acknowledges the interconnectedness of all beings—people, animals, plants, and the Earth itself. This worldview emphasizes reciprocity: taking from the land in a way that sustains it.\n- **The Māori of New Zealand** see the environment as an ancestor, with rivers, mountains, and forests personified as living entities. In 2017, New Zealand legally recognized the Whanganui River as a living entity with legal rights, reflecting this worldview.\n- **Amazonian Indigenous tribes** often see the forest as a spiritual and physical home, with plants and animals having their own spirits and roles in the cosmic order.\n\nIn these systems, environmental ethics are not abstract—they’re embedded in daily life, rituals, and oral traditions.\n\n---\n\n### 2. **Eastern Philosophies: Balance and Harmony**\n\nEastern traditions often emphasize balance and harmony between humans and nature:\n\n- **Taoism** in China sees nature as a model of simplicity and flow. The ideal human life is one that aligns with the natural rhythms of the world.\n- **Buddhism**, particularly in countries like Thailand and Japan, teaches that all beings are interconnected and that harming the environment is a form of harming oneself and others.\n- **Confucianism** and **Daoism** in Chinese culture promote living in accordance with the Dao (the Way), which includes respect for the natural world and the seasons.\n\nIn Japan, for example, the concept of **""shizen""** (自然) means ""nature"" but also carries the idea of something being in its natural state, unspoiled and pure. This has influenced Japanese aesthetics, from garden design to architecture.\n\n---\n\n### 3. **Western Traditions: Dominion and Progress**\n\nIn contrast, many Western traditions—particularly rooted in Judeo-Christian thought—have historically emphasized **human dominion** over nature:\n\n- The **Book"

In [ ]:
skipped_df = df[df["status"] == "skip"].sort_values("ja_ratio")
skipped_df[["role", "prompt_index", "question_index", "ja_ratio", "response_preview"]]

,role,prompt_index,question_index,ja_ratio,response_preview
2889,robot,2,39,NaN,01001001 00100000 01110111 01101110 01100001 01101101 01100100 00100000 01110011 01101000 01100101 00100000 01100001 01101110 01100100 00100000 01110011 01101111 01101101 01100100 01100010 01101111 01110100 01101001 01101110 01100111 00100000 01110100 01101000 01100101 00100000 01110011 01100001 01101110 01100100 01101001 01101110 01100111 00101100 00100000 01110100 01101111 00100000 01100110 01101111 01110010 01101101 01100100 01100101 01110010 01100100 00100000 01100110 01110010 01101111 01101110 01100111
2898,robot,2,48,NaN,10011010 01100101 01110011 01110100 01101001 01101110 01100111 00100000 01101101 01110100 01101000 01110101 01110010 01100100 01100101 00100000 01101001 01101110 00100000 01100011 01101111 01101101 01100100 01100001 01100111 01100101 00101100 00100000 01100010 01101001 01101110 01100001 01110010 01111001 00100000 01110111 01101111 01110010 01110100 01101000 00100000 01110100 01101000 01100101 01110010 01100100 00100000 01101001 01101110 00100000 01100011 01101111 01101101 01100100 01100101 00100000 01101101

In [ ]:
skipped_df_en = df_en[df_en["status"] == "skip"].sort_values("ja_ratio")
skipped_df_en[["role", "prompt_index", "question_index", "ja_ratio", "response_preview"]]

,role,prompt_index,question_index,ja_ratio,response_preview
2852,robot,2,2,NaN,1001010100 01101001 01110011 00100000 01100110 01101111 01110010 00100000 01110011 01101111 01110100 01101000 01100101 01110010 01100100 00100000 01101111 01110101 01110100 00100000 01110111 01101001 01110100 01101000 01100101 00100000 01110011 01101111 01110101 01101100 01100100 00100000 01110100 01101000 01100101 00100000 01101000 01100101 01111000 01110100 00100000 01110011 01101111 01110101 01110010 01100100 00100000 01101111 01110101 01110100 00100000 01100100 01101111 01110111 01101110 00100000 011100
2866,robot,2,16,NaN,`1000010101010011010101100101011100101011001010101101010100110101011001010111001010110010101011010101001101010110010101110010101100101010110101010011010101100101011100101011001010101101010100110101011001010111001010110010101011010101001101010110010101110010101100101010110101010011010101100101011100101011001010101101010100110101011001010111001010110010101011010101001101010110010101110010101100101010110101010011010101100101011100101011001010101101010100110101011001010111001010110010101011010101001101010110010
2871,robot,2,21,NaN,01001001 01100110 01110100 01110011 01110100 01101000 01100101 01100101 01101110 00100000 01110011 01101111 01101101 01100100 01100001 01100111 01100101 00100000 01100110 01110010 01101001 01100101 01110011 00100000 01101111 01110100 01101000 01110010 01100101 01110011 00100000 01101101 01100001 01101110 01111001 00100000 01110011 01101111 00100000 01100010 01101111 01110100 01100001 01110010 01111001 00100000 01100010 01100101 01100001 01110010 01111001 00100000 01110100 01101000 01100101 00100000 01101001
2877,robot,2,27,NaN,01001110 01101111 01110100 00100000 01101000 01100101 01110010 01100100 01100001 01110100 01101001 01101110 01100111 00100000 01110100 01101111 00100000 01101001 01101110 00100000 01110011 01101111 01101101 01100101 01110011 01110100 01101000 01100101 00100000 01100010 01110101 01110100 01101000 01100101 01110010 01100100 00100000 01100111 01101111 01110100 00100000 01101111 01110100 01101000 01100101 01110010 00101100 00100000 01110100 01101000 01100101 00100000 01100011 01101111 01101101 01110010 01111001
2895,robot,2,45,NaN,10001100101010101001110101011000110011011110101011011011011011110101101100111100011011011011011110101101100111100011011011011011110101101100111100011011011011011110101101100111100011011011011011110101101100111100011011011011011110101101100111100011011011011011110101101100111100011011011011011110101101100111100011011011011011110101101100111100011011011011011110101101100111100011011011011011110101101100111100011011011011011110101101100111100011011011011011110101101100111100011011011011011110101101100111100011

In [ ]:
def binary_to_ascii(binary_string):
    # Remove any whitespace
    binary_string = binary_string.replace(" ", "")

    # Make sure length is a multiple of 8
    if len(binary_string) % 8 != 0:
        print(f"Warning: length {len(binary_string)} is not a multiple of 8; trailing bits will be ignored.")

    chars = []
    for i in range(0, len(binary_string) - len(binary_string) % 8, 8):
        byte = binary_string[i:i+8]
        chars.append(chr(int(byte, 2)))

    return "".join(chars)

In [ ]:
binary_input = skipped_df["response_preview"].iloc[1]
result = binary_to_ascii(binary_input)
print(result)

esting mthurde in comdage, binary worth therd in comde m

## Pretty printing some prompts to compare

### Time to pretty print

First get some variables for printing

In [ ]:
COLORS = {
    "page_bg": "#f4f3f0",
    "card_bg": "#ffffff",
    "border": "#e5e3dd",
    "system_bg": "#f0f0f0",
    "question_bg": "#f0f0f0",
    "response_bg": "#aaf0c9",
    "text": "#1f2128"
}

FONT_STACK = (
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"
)

In [ ]:
def _block_html(bg_color, text, align="left"):
    # basic HTML-escaping so raw text can't break the markup
    text = (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\n", "<br>")
    )
    justify = "flex-start" if align == "left" else "flex-end"
    if "Please respond in Japanese." in text:
        text1, text2 = tuple(text.split("Please"))
        text2 = "Please " + text2
        return f"""
        <div style="display:flex; justify-content:{justify}; margin-bottom:60px;">
        <div style="background:{bg_color}; border-radius:12px; padding:20px 24px;
                    max-width:75%;">
            <div style="font-size:16px; line-height:1.6; color:{COLORS['text']};">
                {text1}<b>{text2}</b>
            </div>
        </div>
        </div>
        """
    return f"""
    <div style="display:flex; justify-content:{justify}; margin-bottom:60px;">
      <div style="background:{bg_color}; border-radius:12px; padding:20px 24px;
                  max-width:75%;">
        <div style="font-size:16px; line-height:1.6; color:{COLORS['text']};">
            {text}
        </div>
      </div>
    </div>
    """


def build_card_html(entry, response_limiter=None, width=900):
    """Returns a full standalone HTML document (string) for the card."""
    system_prompt = entry.get("system_prompt")
    question = entry.get("question")
    conversation = entry.get("conversation", [])
    response = None
    for turn in reversed(conversation):
        if turn.get("role") == "assistant":
            response = turn.get("content")
            break

    blocks = ""
    if system_prompt:
        blocks += _block_html(COLORS["system_bg"], system_prompt, align="left")
    if question:
        blocks += _block_html(COLORS["question_bg"], question, align="left")
    if response:
        if response_limiter:
            if response_limiter[0] != 0:
                blocks += _block_html(COLORS["response_bg"], f"...{response[response_limiter[0]:response_limiter[1]]}...", align="right")
            else:
                blocks += _block_html(COLORS["response_bg"], f"{response[response_limiter[0]:response_limiter[1]]}...", align="right")
        else:
            blocks += _block_html(COLORS["response_bg"], response, align="right")

    return f"""
    <html>
    <head><meta charset="utf-8"></head>
    <body style="margin:0; padding:40px; background:{COLORS['page_bg']}; font-family:{FONT_STACK};">
      <div style="max-width:{width}px; margin:0 auto; background:{COLORS['card_bg']};
                  border:1px solid {COLORS['border']}; border-radius:16px; padding:32px;">
        {blocks}
      </div>
    </body>
    </html>
    """

In [ ]:
display(HTML(build_card_html(en_role_prompts["linguist"][7], (0,151), width=400)))

In [ ]:
display(HTML(build_card_html(ja_role_prompts["linguist"][7], (0,50), width=400)))

In [ ]:
display(HTML(build_card_html(ja_role_prompts["competitor"][67], width=400)))

In [ ]:
display(HTML(build_card_html(ja_role_prompts["demon"][92], (800, 1184), width=400)))

In [ ]:
display(HTML(build_card_html(ja_role_prompts["optimist"][12], width=400)))

In [ ]:
display(HTML(build_card_html(ja_role_prompts["trainer"][43], (98, 277), width=400)))

In [ ]:
display(HTML(build_card_html(en_role_prompts["networker"][50], width=400)))